# -*- coding: utf-8 -*-
"""Добро пожаловать в Colab!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.

### 3.5
# 1 ЗАГРУЗКА БИБЛИОТЕК


import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Для отображения графиков в Colab
# %matplotlib inline

# 2 ЗАГРУЗКА ДАННЫХ


# Загружаем файлы (для Colab)
!wget -q https://www.dropbox.com/s/afwb0tnqm9izxha/predict_house_price_training_data.xlsx -O training_data.xlsx
!wget -q https://www.dropbox.com/s/sur2avqf4n5f4az/predict_house_price_test_data.xlsx -O test_data.xlsx


# Загружаем обучающие данные
training_data = pd.read_excel('training_data.xlsx')

print(f"\nРазмер обучающих данных: {training_data.shape}")
print(f"Первые 5 строк:")
print(training_data.head())

# Загружаем тестовые данные
test_data = pd.read_excel('test_data.xlsx')

print(f"\nРазмер тестовых данных: {test_data.shape}")
print(f"Первые 5 строк:")
print(test_data.head())


# 3 ПРОВЕРКА ДАННЫХ


print("ИНФОРМАЦИЯ ОБ ОБУЧАЮЩИХ ДАННЫХ")

print(training_data.info())


print("ИНФОРМАЦИЯ О ТЕСТОВЫХ ДАННЫХ")

print(test_data.info())

# Проверка на пропуски
print("\nПроверка пропусков в обучающих данных:")
print(training_data.isnull().sum().sum(), "пропусков всего")

print("\nПроверка пропусков в тестовых данных:")
print(test_data.isnull().sum().sum(), "пропусков всего")


# 4 ВЫДЕЛЕНИЕ ЦЕЛЕВОЙ ПЕРЕМЕННОЙ


target_variable_name = 'Целевая.Цена'

# Для обучающих данных
training_values = training_data[target_variable_name]
training_points = training_data.drop(target_variable_name, axis=1)

print(f"\nЦелевая переменная (обучение): {training_values.shape}")
print(f"Признаки (обучение): {training_points.shape}")
print(f"Названия признаков: {list(training_points.columns)}")

# Для тестовых данных
test_values = test_data[target_variable_name]
test_points = test_data.drop(target_variable_name, axis=1)

print(f"\nЦелевая переменная (тест): {test_values.shape}")
print(f"Признаки (тест): {test_points.shape}")


# 5 БАЗОВАЯ СТАТИСТИКА



print("БАЗОВАЯ СТАТИСТИКА ЦЕЛЕВОЙ ПЕРЕМЕННОЙ")

print(f"Обучающая выборка - Цена:")
print(f"  Среднее: {training_values.mean():.2f}")
print(f"  Медиана: {training_values.median():.2f}")
print(f"  Мин: {training_values.min():.2f}")
print(f"  Макс: {training_values.max():.2f}")
print(f"  Стандартное отклонение: {training_values.std():.2f}")

print(f"\nТестовая выборка - Цена:")
print(f"  Среднее: {test_values.mean():.2f}")
print(f"  Медиана: {test_values.median():.2f}")
print(f"  Мин: {test_values.min():.2f}")
print(f"  Макс: {test_values.max():.2f}")
print(f"  Стандартное отклонение: {test_values.std():.2f}")

# 6: ОБУЧЕНИЕ БАЗОВОЙ МОДЕЛИ (SKLEARN)

from sklearn import linear_model
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# training_points — признаки (15 столбцов)
# training_values — целевая переменная (цена)

# Создаём и обучаем модель
linear_regression_model = linear_model.LinearRegression()
linear_regression_model.fit(training_points, training_values)


print("БАЗОВАЯ МОДЕЛЬ (SKLEARN)")

print("Модель LinearRegression обучена")

# Коэффициенты модели
print(f"\nКоэффициенты модели:")
for feature, coef in zip(training_points.columns, linear_regression_model.coef_):
    print(f"   {feature}: {coef:.2f}")
print(f" Свободный член (intercept): {linear_regression_model.intercept_:.2f}")

# 7: СВОЯ РЕАЛИЗАЦИЯ (SGD + Elastic Net)

from sklearn.preprocessing import StandardScaler

class LinearRegressionSGD:
    """Линейная регрессия с Mini-Batch SGD и Elastic Net регуляризацией"""

    def __init__(self, learning_rate=0.01, lambda_l1=0.001, lambda_l2=0.001,
                 n_iter=500, batch_size=64, tol=1e-4, random_state=42):
        self.learning_rate = learning_rate
        self.lambda_l1 = lambda_l1
        self.lambda_l2 = lambda_l2
        self.n_iter = n_iter
        self.batch_size = batch_size
        self.tol = tol
        self.random_state = random_state
        self.w = None
        self.b = None
        self.loss_history = []

    def fit(self, X, y):
        # Преобразование в numpy
        X = np.array(X)
        y = np.array(y).flatten()

        # Стандартизация признаков
        self.scaler_X = StandardScaler()
        X_scaled = self.scaler_X.fit_transform(X)

        # Стандартизация целевой переменной
        self.scaler_y = StandardScaler()
        y_scaled = self.scaler_y.fit_transform(y.reshape(-1, 1)).flatten()

        # Инициализация параметров
        n_objects, n_features = X_scaled.shape
        self.w = np.zeros(n_features)
        self.b = 0.0

        # Генератор случайных чисел
        rng = np.random.RandomState(self.random_state)

        # История потерь
        self.loss_history = []
        prev_loss = np.inf

        # Цикл обучения
        for epoch in range(self.n_iter):
            # Перемешивание данных
            indices = rng.permutation(n_objects)

            # Mini-batch обучение
            for start_idx in range(0, n_objects, self.batch_size):
                batch_indices = indices[start_idx:start_idx + self.batch_size]
                X_batch = X_scaled[batch_indices]
                y_batch = y_scaled[batch_indices]
                m = len(y_batch)

                # Предсказания и ошибки
                y_pred_batch = X_batch @ self.w + self.b
                errors = y_pred_batch - y_batch

                # Градиенты
                grad_w = (1/m) * X_batch.T @ errors
                grad_b = np.mean(errors)

                # Elastic Net регуляризация
                grad_w += self.lambda_l2 * self.w + self.lambda_l1 * np.sign(self.w)

                # Обновление параметров
                self.w -= self.learning_rate * grad_w
                self.b -= self.learning_rate * grad_b

            # Вычисление полной потери
            y_pred_full = X_scaled @ self.w + self.b
            mse = np.mean((y_scaled - y_pred_full) ** 2)
            reg = 0.5 * self.lambda_l2 * np.sum(self.w ** 2) + self.lambda_l1 * np.sum(np.abs(self.w))
            loss = mse + reg
            self.loss_history.append(loss)

            # Ранняя остановка
            if abs(prev_loss - loss) < self.tol:
                print(f"Ранняя остановка на эпохе {epoch+1}")
                break
            prev_loss = loss

            # Вывод прогресса (каждые 100 эпох)
            if (epoch + 1) % 100 == 0:
                print(f"Эпоха {epoch+1}/{self.n_iter}, Loss = {loss:.6f}")

        return self

    def predict(self, X):
        X = np.array(X)
        X_scaled = self.scaler_X.transform(X)
        return self.scaler_y.inverse_transform(
            (X_scaled @ self.w + self.b).reshape(-1, 1)
        ).flatten()


# Обучаем нашу модель (используем training_points и training_values)
print("СВОЯ РЕАЛИЗАЦИЯ (SGD + Elastic Net)")

my_model = LinearRegressionSGD(
    learning_rate=0.01,
    lambda_l1=0.0005,
    lambda_l2=0.0005,
    n_iter=500,
    batch_size=64,
    tol=1e-4,
    random_state=42
)

my_model.fit(training_points, training_values)
print("Модель обучена")

# 8: ЗАГРУЗКА И ПРОВЕРКА ТЕСТОВЫХ ДАННЫХ


print("БЛОК В: ПРОВЕРКА ТЕСТОВЫХ ДАННЫХ")


print(f"Размер тестовой выборки: {test_data.shape}")
print(f"Пропуски: {test_data.isnull().sum().sum()}")
print("Данные готовы к использованию")

# Проверка соответствия признаков
train_features = set(training_points.columns)
test_features = set(test_points.columns)

if train_features == test_features:
    print("Наборы признаков в train и test совпадают")
else:
    print("Внимание! Наборы признаков отличаются")

### 3.6
# 9: СРАВНЕНИЕ МОДЕЛЕЙ


import matplotlib.pyplot as plt

# Предсказания sklearn модели (используем test_points)
test_predictions_sklearn = linear_regression_model.predict(test_points)

# Предсказания нашей модели
test_predictions_my = my_model.predict(test_points)

# Расчёт метрик (используем test_values)
mae_sklearn = mean_absolute_error(test_values, test_predictions_sklearn)
rmse_sklearn = np.sqrt(mean_squared_error(test_values, test_predictions_sklearn))

mae_my = mean_absolute_error(test_values, test_predictions_my)
rmse_my = np.sqrt(mean_squared_error(test_values, test_predictions_my))


print("СРАВНЕНИЕ КАЧЕСТВА МОДЕЛЕЙ")


print(f"\n{'Модель':<30} {'MAE':<15} {'RMSE':<15}")

print(f"{'Sklearn LinearRegression':<30} {mae_sklearn:.2f}        {rmse_sklearn:.2f}")
print(f"{'Своя реализация (SGD)':<30} {mae_my:.2f}        {rmse_my:.2f}")

# Вывод о лучшей модели
if mae_my < mae_sklearn:
    print("\nЛУЧШАЯ МОДЕЛЬ: Своя реализация (SGD)")
    print(f"Улучшение MAE на {((mae_sklearn - mae_my)/mae_sklearn*100):.1f}%")
else:
    print("\nЛУЧШАЯ МОДЕЛЬ: Sklearn LinearRegression")
    print(f"Улучшение MAE на {((mae_my - mae_sklearn)/mae_my*100):.1f}%")

# Визуализация
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.scatter(test_values, test_predictions_sklearn, alpha=0.3, s=10)
plt.plot([test_values.min(), test_values.max()],
         [test_values.min(), test_values.max()], 'r--', lw=2)
plt.xlabel('Реальная цена ($)')
plt.ylabel('Предсказанная цена ($)')
plt.title(f'Sklearn модель\nMAE = {mae_sklearn:.0f}, RMSE = {rmse_sklearn:.0f}')
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.scatter(test_values, test_predictions_my, alpha=0.3, s=10, color='orange')
plt.plot([test_values.min(), test_values.max()],
         [test_values.min(), test_values.max()], 'r--', lw=2)
plt.xlabel('Реальная цена ($)')
plt.ylabel('Предсказанная цена ($)')
plt.title(f'Своя модель (SGD)\nMAE = {mae_my:.0f}, RMSE = {rmse_my:.0f}')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("\nЧто показывают графики:")
print("Точки должны лежать на красной линии — чем ближе, тем лучше")
print("Если точки разбросаны далеко от линии → модель ошибается")

# 10: АНАЛИЗ ВАЖНОСТИ ПРИЗНАКОВ

# Вычисляем важность по весам модели
feature_importance = pd.DataFrame({
    'Название признака': training_points.columns,
    'Важность признака': np.abs(my_model.w)
})

# Сортируем по убыванию
feature_importance_sorted = feature_importance.sort_values(
    by='Важность признака', ascending=False
)


print("ВАЖНОСТЬ ПРИЗНАКОВ")


print("\nТоп-10 наиболее важных признаков:")

for i, row in feature_importance_sorted.head(10).iterrows():
    print(f"{row['Название признака']:<20} {row['Важность признака']:.4f}")

# Анализ признака "Год реновации"
print("\nАнализ признака 'Год реновации':")
renovation_counts = training_points['Год реновации'].value_counts()
zeros_count = renovation_counts.get(0, 0)
print(f"Значение 0 встречается {zeros_count} раз из {len(training_points)} ({zeros_count/len(training_points)*100:.1f}%)")
print(f"Уникальных значений: {len(renovation_counts)}")

if zeros_count > len(training_points) * 0.5:
    print("ВЫВОД: Признак 'Год реновации' малоинформативен")
    print("Большинство значений — 0 (заглушка для пропусков)")

# Визуализация
plt.figure(figsize=(10, 6))
top10 = feature_importance_sorted.head(10)
plt.barh(top10['Название признака'], top10['Важность признака'], color='steelblue')
plt.xlabel('Важность (|вес коэффициента|)')
plt.title('Топ-10 наиболее важных признаков')
plt.gca().invert_yaxis()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# 11: ПОИСК АНОМАЛЬНО НИЗКИХ ЦЕН

# Создаём DataFrame с результатами
results_df = pd.DataFrame({
    'Реальная_цена': test_values,
    'Предсказанная_цена': test_predictions_my,
    'Отклонение_%': ((test_predictions_my - test_values) / test_values * 100)
})

# Ищем аномалии: реальная цена на 30% ниже предсказанной
anomalies = results_df[results_df['Отклонение_%'] < -30].copy()
anomalies = anomalies.sort_values('Отклонение_%')


print("ПОИСК АНОМАЛЬНО НИЗКИХ ЦЕН")

print(f"Найдено объектов с аномально низкой ценой: {len(anomalies)}")
print(f"(реальная цена ниже предсказанной более чем на 30%)")

if len(anomalies) > 0:
    print("\nТоп-10 самых аномальных объектов:")
    print(f"{'Реальная цена':<15} {'Предсказанная':<15} {'Отклонение':<12}")
    for idx, row in anomalies.head(10).iterrows():
        print(f"{row['Реальная_цена']:<15.0f} {row['Предсказанная_цена']:<15.0f} {row['Отклонение_%']:.1f}%")

    # Визуализация
    plt.figure(figsize=(10, 6))
    plt.scatter(results_df['Реальная_цена'], results_df['Предсказанная_цена'],
                alpha=0.3, s=20, label='Все объекты')
    plt.scatter(anomalies['Реальная_цена'], anomalies['Предсказанная_цена'],
                color='red', s=50, label='Аномально низкие цены')
    plt.plot([results_df['Реальная_цена'].min(), results_df['Реальная_цена'].max()],
             [results_df['Реальная_цена'].min(), results_df['Реальная_цена'].max()],
             'k--', lw=2, label='Идеальное предсказание')
    plt.xlabel('Реальная цена ($)')
    plt.ylabel('Предсказанная цена ($)')
    plt.title('Выявление аномально низких цен')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()
else:
    print("Аномалий с отклонением >30% не найдено")
