# -*- coding: utf-8 -*-
"""Добро пожаловать в Colab!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Лабораторная работа 2: GBDT для задачи Traffic & Mobility на геоданных Санкт-Петербурга


# 0. Установка и импорт библиотек

!pip install osmnx geopandas shapely scikit-learn matplotlib contextily mapclassify lightgbm xgboost catboost

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import geopandas as gpd
import osmnx as ox
import networkx as nx
import matplotlib.pyplot as plt

from shapely.geometry import box, Point
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.inspection import permutation_importance
from sklearn.neighbors import BallTree

# Импорт трёх GBDT моделей
import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostRegressor

# Настройки OSMnx
ox.settings.use_cache = True
ox.settings.log_console = False

print("Библиотеки загружены")
print(f"LightGBM version: {lgb.__version__}")
print(f"XGBoost version: {xgb.__version__}")


# 1. Область исследования

# Центральная часть Санкт-Петербурга
bbox = (30.18, 59.86, 30.55, 60.03)
polygon_wgs = box(*bbox)

print("Область исследования:")
print(polygon_wgs)


# 2. Загрузка уличной сети из OpenStreetMap

print("\nЗагрузка дорожной сети Санкт-Петербурга...")

G = ox.graph_from_polygon(
    polygon_wgs,
    network_type="drive",
    simplify=True,
    retain_all=False
)

# Получаем GeoDataFrame узлов и рёбер
nodes, edges = ox.graph_to_gdfs(G, nodes=True, edges=True)

print(f"Загружено узлов: {len(nodes)}")
print(f"Загружено рёбер: {len(edges)}")
edges.head()


# 3. Приведение к метрической системе координат

LOCAL_CRS = "EPSG:32636"  # UTM zone 36N для Санкт-Петербурга
edges_m = edges.to_crs(LOCAL_CRS)

print(f"CRS после преобразования: {edges_m.crs}")


# 4. Базовые геометрические признаки дорожных сегментов

roads = edges_m.copy()

# Длина сегмента в метрах
roads["length_m_geom"] = roads.geometry.length

# Центроид сегмента
roads["centroid_x"] = roads.geometry.centroid.x
roads["centroid_y"] = roads.geometry.centroid.y

# Функция для прямого расстояния между началом и концом LineString
def straight_distance(geom):
    coords = list(geom.coords)
    x1, y1 = coords[0]
    x2, y2 = coords[-1]
    return np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

roads["straight_dist_m"] = roads.geometry.apply(straight_distance)

# Извилистость: отношение длины линии к прямому расстоянию
roads["sinuosity"] = roads["length_m_geom"] / roads["straight_dist_m"].replace(0, np.nan)
roads["sinuosity"] = roads["sinuosity"].replace([np.inf, -np.inf], np.nan).fillna(1)

# Направление дороги в радианах
def segment_angle(geom):
    coords = list(geom.coords)
    x1, y1 = coords[0]
    x2, y2 = coords[-1]
    dx = x2 - x1
    dy = y2 - y1
    return np.arctan2(dy, dx)

roads["angle_rad"] = roads.geometry.apply(segment_angle)

print("Статистика геометрических признаков:")
print(roads[["length_m_geom", "straight_dist_m", "sinuosity", "angle_rad"]].describe())


# 5. Категориальные признаки дороги

roads["highway_str"] = roads["highway"].apply(lambda x: ",".join(x) if isinstance(x, list) else str(x))

# Создаём dummy-переменные для highway_str
highway_dummies = pd.get_dummies(roads["highway_str"], prefix="highway")
roads = pd.concat([roads, highway_dummies], axis=1)

print("Создано one-hot признаков для highway:", highway_dummies.shape[1])
highway_dummies.head()


# 6. Загрузка POI и остановок общественного транспорта

print("\nЗагрузка POI и остановок...")

# Теги городских объектов
poi_tags = {
    "amenity": True,
    "shop": True,
    "office": True,
    "tourism": True,
    "leisure": True,
}

stop_tags = {
    "highway": "bus_stop",
    "public_transport": True,
    "railway": ["station", "subway_entrance", "tram_stop"]
}

# Загружаем POI и остановки
pois = ox.features_from_polygon(polygon_wgs, tags=poi_tags)
stops = ox.features_from_polygon(polygon_wgs, tags=stop_tags)

print(f"POI загружено: {pois.shape[0]}")
print(f"Остановок загружено: {stops.shape[0]}")


# 7. Подготовка точек POI и остановок

def to_points(gdf, crs_target):
    gdf = gdf.copy()
    gdf = gdf.to_crs(crs_target)
    gdf["geometry"] = gdf.geometry.representative_point()
    return gdf

# Применяем функцию к pois и stops
pois_m = to_points(pois, roads.crs)
stops_m = to_points(stops, roads.crs)

# Очищаем от пустых геометрий
pois_m = pois_m[~pois_m.geometry.is_empty & pois_m.geometry.notna()]
stops_m = stops_m[~stops_m.geometry.is_empty & stops_m.geometry.notna()]

print(f"POI после обработки: {len(pois_m)}")
print(f"Остановок после обработки: {len(stops_m)}")
pois_m.head()


# 8. Пространственные признаки через BallTree

def nearest_and_count(source_gdf, target_gdf, radius=300):
    """
    source_gdf: объекты, для которых считаем признаки, например дороги
    target_gdf: объекты окружения, например POI или остановки
    radius: радиус поиска в метрах
    """
    source_coords = np.vstack([
        source_gdf.geometry.centroid.x,
        source_gdf.geometry.centroid.y
    ]).T

    target_coords = np.vstack([
        target_gdf.geometry.x,
        target_gdf.geometry.y
    ]).T

    tree = BallTree(target_coords, metric="euclidean")

    # Расстояние до ближайшего объекта
    dist, ind = tree.query(source_coords, k=1)
    nearest_dist = dist[:, 0]

    # Количество объектов в радиусе
    counts = tree.query_radius(source_coords, r=radius, count_only=True)

    return nearest_dist, counts

# Для расчётов используем центроиды дорог как точки
road_points = roads.copy()
road_points["geometry"] = road_points.geometry.centroid

roads["dist_to_poi_m"], roads["poi_count_300m"] = nearest_and_count(road_points, pois_m, radius=300)
roads["dist_to_stop_m"], roads["stop_count_300m"] = nearest_and_count(road_points, stops_m, radius=300)

print("Статистика пространственных признаков:")
print(roads[["dist_to_poi_m", "poi_count_300m", "dist_to_stop_m", "stop_count_300m"]].describe())


# 9. Графовые признаки дорожной сети

# Сброс индекса для работы с u, v
roads = roads.reset_index()

# Словарь степеней узлов
node_degree = dict(G.degree())

roads["u_degree"] = roads["u"].map(node_degree)
roads["v_degree"] = roads["v"].map(node_degree)
roads["mean_node_degree"] = (roads["u_degree"] + roads["v_degree"]) / 2

print("Статистика графовых признаков:")
print(roads[["u_degree", "v_degree", "mean_node_degree"]].describe())


# 10. Формирование учебной целевой переменной

def minmax(s):
    return (s - s.min()) / (s.max() - s.min() + 1e-9)

# Нормировка признаков
roads["length_norm"] = minmax(roads["length_m_geom"].clip(upper=roads["length_m_geom"].quantile(0.99)))
roads["poi_count_norm"] = minmax(roads["poi_count_300m"])
roads["stop_count_norm"] = minmax(roads["stop_count_300m"])
roads["degree_norm"] = minmax(roads["mean_node_degree"])
roads["near_poi_norm"] = 1 - minmax(roads["dist_to_poi_m"].clip(upper=roads["dist_to_poi_m"].quantile(0.99)))
roads["near_stop_norm"] = 1 - minmax(roads["dist_to_stop_m"].clip(upper=roads["dist_to_stop_m"].quantile(0.99)))

rng = np.random.default_rng(42)
noise = rng.normal(0, 0.05, size=len(roads))

# Формула целевой переменной
roads["traffic_load_score"] = (
    0.25 * roads["length_norm"] +
    0.20 * roads["poi_count_norm"] +
    0.15 * roads["stop_count_norm"] +
    0.20 * roads["degree_norm"] +
    0.10 * roads["near_poi_norm"] +
    0.10 * roads["near_stop_norm"] +
    noise
)

roads["traffic_load_score"] = roads["traffic_load_score"].clip(0, 1)

print("Статистика целевой переменной:")
print(roads["traffic_load_score"].describe())



# 11. Подготовка признаков для модели

# Базовые числовые признаки
base_features = [
    "length_m_geom",
    "straight_dist_m",
    "sinuosity",
    "angle_rad",
    "centroid_x",
    "centroid_y",
    "dist_to_poi_m",
    "poi_count_300m",
    "dist_to_stop_m",
    "stop_count_300m",
    "mean_node_degree",
]

# One-hot признаки для highway
highway_features = list(highway_dummies.columns)

# Объединяем списки признаков
feature_cols = base_features + highway_features

# Подготавливаем X и y
X = roads[feature_cols].replace([np.inf, -np.inf], np.nan).fillna(0)
y = roads["traffic_load_score"]

#  Очищаем имена признаков от специальных символов
# LightGBM не поддерживает: [ ] , < > : ; и другие спецсимволы
def clean_feature_name(name):
    """Очищает имя признака от символов, которые не поддерживает LightGBM"""
    # Заменяем проблемные символы на подчеркивания
    for char in ['[', ']', '(', ')', ',', ';', ':', '<', '>', '/', '\\', '|', '=', '+', '*', '&', '^', '%', '$', '#', '@', '!', '~', '`']:
        name = name.replace(char, '_')
    # Убираем множественные подчеркивания
    while '__' in name:
        name = name.replace('__', '_')
    # Убираем подчеркивания в начале и конце
    name = name.strip('_')
    return name

# Очищаем имена колонок
X.columns = [clean_feature_name(col) for col in X.columns]

# Обновляем список признаков после очистки
feature_cols_cleaned = list(X.columns)

print(f"Признаков: {X.shape[1]}")
print(f"Объектов: {X.shape[0]}")
print("\nПервые 10 признаков (очищенные имена):")
print(feature_cols_cleaned[:10])
print(f"... + {len([c for c in feature_cols_cleaned if c.startswith('highway_')])} highway-признаков")


# 12. Разделение на train/test

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

print(f"Размер обучающей выборки: {X_train.shape}")
print(f"Размер тестовой выборки: {X_test.shape}")


# 13. Обучение трёх GBDT моделей (Задание 12)

print("\n" + "="*50)
print("Обучение трёх моделей GBDT")
print("="*50)

# ---- Модель 1: LightGBM ----
print("\n1. Обучение LightGBM...")
model_lgb = lgb.LGBMRegressor(
    n_estimators=300,
    learning_rate=0.1,
    num_leaves=31,
    min_child_samples=20,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    verbose=-1
)
model_lgb.fit(X_train, y_train)
print("LightGBM обучен")

# ---- Модель 2: XGBoost ----
print("\n2. Обучение XGBoost...")
model_xgb = xgb.XGBRegressor(
    n_estimators=300,
    learning_rate=0.1,
    max_depth=6,
    min_child_weight=1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    verbosity=0
)
model_xgb.fit(X_train, y_train)
print("XGBoost обучен")

# ---- Модель 3: CatBoost ----
print("\n3. Обучение CatBoost...")
model_cat = CatBoostRegressor(
    iterations=300,
    learning_rate=0.1,
    depth=6,
    l2_leaf_reg=1,
    subsample=0.8,
    random_seed=42,
    verbose=False
)
model_cat.fit(X_train, y_train)
print("CatBoost обучен")


# 14. Оценка качества моделей (Задание 13)

def evaluate_model(model, X_train, X_test, y_train, y_test, name="Модель"):
    """Оценка модели и вывод метрик"""
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    mae_train = mean_absolute_error(y_train, y_train_pred)
    mae_test = mean_absolute_error(y_test, y_test_pred)
    rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
    rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))
    r2_train = r2_score(y_train, y_train_pred)
    r2_test = r2_score(y_test, y_test_pred)

    print(f"\n{name}:")
    print(f"  Train MAE:  {mae_train:.4f}")
    print(f"  Test MAE:   {mae_test:.4f}")
    print(f"  Train RMSE: {rmse_train:.4f}")
    print(f"  Test RMSE:  {rmse_test:.4f}")
    print(f"  Train R²:   {r2_train:.4f}")
    print(f"  Test R²:    {r2_test:.4f}")

    return {
        "name": name,
        "mae_train": mae_train,
        "mae_test": mae_test,
        "rmse_train": rmse_train,
        "rmse_test": rmse_test,
        "r2_train": r2_train,
        "r2_test": r2_test
    }


print("Результаты оценки трёх моделей")

results = []
results.append(evaluate_model(model_lgb, X_train, X_test, y_train, y_test, "LightGBM"))
results.append(evaluate_model(model_xgb, X_train, X_test, y_train, y_test, "XGBoost"))
results.append(evaluate_model(model_cat, X_train, X_test, y_train, y_test, "CatBoost"))

# Сравнение результатов

print("Сравнение моделей (Test MAE):")

for r in sorted(results, key=lambda x: x["mae_test"]):
    print(f"{r['name']}: MAE = {r['mae_test']:.4f}, R² = {r['r2_test']:.4f}")

# Выбираем лучшую модель
best_model_name = min(results, key=lambda x: x["mae_test"])["name"]
best_model = {
    "LightGBM": model_lgb,
    "XGBoost": model_xgb,
    "CatBoost": model_cat
}[best_model_name]

print(f"\nЛучшая модель: {best_model_name}")


# Задание 14: Настройка гиперпараметров для лучшей модели



print(f"Настройка гиперпараметров для {best_model_name}")

def tune_lightgbm():
    """Настройка LightGBM"""
    print("\nНастройка LightGBM...")
    param_grid = {
        'n_estimators': [200, 300],
        'learning_rate': [0.05, 0.1],
        'num_leaves': [31, 63],
        'min_child_samples': [10, 20]
    }

    grid_search = GridSearchCV(
        lgb.LGBMRegressor(random_state=42, n_jobs=-1, verbose=-1),
        param_grid,
        cv=3,
        scoring='neg_mean_absolute_error',
        n_jobs=-1
    )
    grid_search.fit(X_train, y_train)
    return grid_search.best_params_, grid_search.best_estimator_

def tune_xgboost():
    """Настройка XGBoost"""
    print("\nНастройка XGBoost...")
    param_grid = {
        'n_estimators': [200, 300],
        'learning_rate': [0.05, 0.1],
        'max_depth': [4, 6],
        'min_child_weight': [1, 3]
    }

    grid_search = GridSearchCV(
        xgb.XGBRegressor(random_state=42, n_jobs=-1, verbosity=0),
        param_grid,
        cv=3,
        scoring='neg_mean_absolute_error',
        n_jobs=-1
    )
    grid_search.fit(X_train, y_train)
    return grid_search.best_params_, grid_search.best_estimator_

def tune_catboost():
    """Настройка CatBoost"""
    print("\nНастройка CatBoost...")
    param_grid = {
        'iterations': [200, 300],
        'learning_rate': [0.05, 0.1],
        'depth': [4, 6],
        'l2_leaf_reg': [1, 3]
    }

    grid_search = GridSearchCV(
        CatBoostRegressor(random_seed=42, verbose=False),
        param_grid,
        cv=3,
        scoring='neg_mean_absolute_error',
        n_jobs=-1
    )
    grid_search.fit(X_train, y_train)
    return grid_search.best_params_, grid_search.best_estimator_

# Выбираем функцию настройки в зависимости от лучшей модели
tune_functions = {
    "LightGBM": tune_lightgbm,
    "XGBoost": tune_xgboost,
    "CatBoost": tune_catboost
}

best_params, model_optimized = tune_functions[best_model_name]()
print(f"\nЛучшие параметры для {best_model_name}:")
for k, v in best_params.items():
    print(f"  {k}: {v}")

# Оценка оптимизированной модели
y_test_pred_opt = model_optimized.predict(X_test)
mae_test_opt = mean_absolute_error(y_test, y_test_pred_opt)
print(f"\nТестовый MAE оптимизированной модели: {mae_test_opt:.4f}")

# Сравнение с базовой моделью
baseline_mae = min(r["mae_test"] for r in results)
if mae_test_opt < baseline_mae:
    print(f"Оптимизированная модель улучшила результат с {baseline_mae:.4f} до {mae_test_opt:.4f}")
    best_model = model_optimized
else:
    print(f"Базовая модель осталась лучшей (MAE = {baseline_mae:.4f})")

print(f"\nФинальная лучшая модель: {best_model_name}")



# 15. Важность признаков (Permutation Importance)
print("Анализ важности признаков")

perm_importance = permutation_importance(
    best_model,
    X_test,
    y_test,
    n_repeats=5,
    random_state=42,
    scoring='neg_mean_absolute_error'
)

importance_df = pd.DataFrame({
    'feature': X_test.columns,
    'importance': perm_importance.importances_mean
}).sort_values('importance', ascending=False)

print("Топ-15 наиболее важных признаков:")
print(importance_df.head(15))

# Визуализация важности признаков
plt.figure(figsize=(10, 8))
top_features = importance_df.head(15).sort_values('importance', ascending=True)
plt.barh(top_features['feature'], top_features['importance'])
plt.xlabel('Увеличение MAE при перемешивании признака')
plt.title(f'Permutation Importance признаков ({best_model_name})')
plt.tight_layout()
plt.show()



# 16. Прогноз для всех дорожных сегментов и карта (Задание 15)


print("Визуализация прогноза")

# Прогноз для всех сегментов
roads["predicted_traffic_load"] = best_model.predict(X)

# Возвращаем геометрию в WGS84 для удобной визуализации
roads_wgs = gpd.GeoDataFrame(roads, geometry="geometry", crs=edges_m.crs).to_crs(4326)

# Создаем карту
fig, ax = plt.subplots(figsize=(14, 12))

roads_wgs.plot(
    ax=ax,
    column="predicted_traffic_load",
    linewidth=1.5,
    legend=True,
    cmap="inferno",
    legend_kwds={
        'label': 'Прогнозируемая транспортная нагрузка',
        'shrink': 0.8,
        'aspect': 30
    }
)

ax.set_title(
    f"Прогноз потенциальной транспортной нагрузки\nСанкт-Петербург (центральная часть)\nМодель: {best_model_name}",
    fontsize=14
)
ax.set_xlabel("Долгота")
ax.set_ylabel("Широта")
ax.axis('on')
plt.tight_layout()
plt.show()


# 17. Дополнительный анализ ошибок

print("Дополнительный анализ ошибок")

# Сравнение прогноза с истинной целевой переменной для тестовой выборки
test_result = roads.loc[X_test.index].copy()
test_result["y_true"] = y_test.values
test_result["y_pred"] = best_model.predict(X_test)
test_result["error"] = np.abs(test_result["y_true"] - test_result["y_pred"])

# Группировка по типу дороги
error_by_road_type = test_result.groupby("highway_str").agg({
    "error": ["mean", "std", "count"],
    "y_true": "mean",
    "y_pred": "mean"
}).round(4)

error_by_road_type.columns = ["mae", "std_mae", "count", "mean_true", "mean_pred"]
error_by_road_type = error_by_road_type.sort_values("mae", ascending=False)

print("Ошибка прогноза по типам дорог (топ-10):")
print(error_by_road_type.head(10))

# Гистограмма ошибок
plt.figure(figsize=(10, 6))
plt.hist(test_result["error"], bins=50, edgecolor='black', alpha=0.7)
plt.xlabel("Абсолютная ошибка")
plt.ylabel("Количество сегментов")
plt.title(f"Распределение ошибок прогноза ({best_model_name})")
plt.axvline(x=test_result["error"].mean(), color='r', linestyle='--',
            label=f'Средняя ошибка: {test_result["error"].mean():.3f}')
plt.legend()
plt.show()

# Scatter plot: предсказанные vs истинные значения
plt.figure(figsize=(8, 8))
plt.scatter(test_result["y_true"], test_result["y_pred"], alpha=0.3, s=10)
plt.plot([0, 1], [0, 1], 'r--', label='Идеальное предсказание')
plt.xlabel("Истинное значение")
plt.ylabel("Предсказанное значение")
plt.title(f"Предсказанные vs Истинные значения ({best_model_name})")
plt.legend()
plt.show()


# Итоговые результаты

print("ИТОГОВЫЕ РЕЗУЛЬТАТЫ")

print(f"\nЛучшая модель: {best_model_name}")
print(f"Test MAE: {min(r['mae_test'] for r in results):.4f}")
print(f"Test R²: {max(r['r2_test'] for r in results):.4f}")

print("\nСравнение всех моделей:")
for r in sorted(results, key=lambda x: x["mae_test"]):
    print(f"  {r['name']}: MAE = {r['mae_test']:.4f}, R² = {r['r2_test']:.4f}")

print("\nТоп-5 важнейших признаков:")
for i, row in importance_df.head(5).iterrows():
    print(f"  {row['feature']}: {row['importance']:.4f}")

print("\nЛаба выполнена ура")
